debug: false

server:
  context-path: /
  port: 8080
  error:
    whitelabel:
      enabled: false


spring:
  jpa:
    hibernate:
      ddl-auto: true
    generate-ddl: false
    database: mysql
    show-sql: true
  datasource:
    initialize: true
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timeline?useUnicode=true&amp;characterEncoding=utf-8
    username: timeline
    password: timeline
  thymeleaf:
    cache: false
#    check-template-location: false



#spring.thymeleaf.cache: false
#spring.thymeleaf.check-template-location: false
#spring.thymeleaf.enabled: true
#spring.thymeleaf.mode: LEGACYHTML5
#spring.thymeleaf.mode: jsp



security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: user
#    role: ADMIN
  enable-csrf: false