DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
  `USER_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '사용자 고유 키',
  `NAME` varchar(20) DEFAULT NULL COMMENT '사용자 이름',
  `PASSWORD` varchar(255) NOT NULL DEFAULT '' COMMENT '사용자 비밀번호',
  `CREATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '사용자 추가 일시',
  `LAST_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '사용자 수정 일시',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


LOCK TABLES `USERS` WRITE;
INSERT INTO `USERS` (`NAME`, `PASSWORD`, `CREATED_DATE`, `LAST_UPDATE`)
VALUES ('freegians','freegians',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `USERS` (`NAME`, `PASSWORD`, `CREATED_DATE`, `LAST_UPDATE`)
VALUES ('user1','user1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `USERS` (`NAME`, `PASSWORD`, `CREATED_DATE`, `LAST_UPDATE`)
VALUES ('user2','user2',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
UNLOCK TABLES;

